version: 2
jobs:
  build:
    docker:
      - image: paperist/alpine-texlive-ja:2017
    steps:
      - run: apk add --no-cache ca-certificates
      - run: apk add aws-cli --update-cache --allow-untrusted --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
      - run: tlmgr install fontawesome multibib
      - checkout
      - run: latexmk cv.tex
      - deploy:
          name: Deploy to S3
          command: aws s3 cp cv.pdf s3://keichi.net/cv_takahashi.pdf
